### ISSUE TITLE
Missing images (plots) under InspiRation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/workshops#1]
At http://tutorials.iq.harvard.edu/R/Rintro/Rintro.html under "InspiRation" one of the images is visible but two don't seem to be, such as a map of Cambridge and a plot about Australia:

![introduction_to_r_-_2015-09-11_09 50 59](https://cloud.githubusercontent.com/assets/21006/9816383/a770f6f6-586a-11e5-9372-b5dcc32c6cef.png)

**Comment by izahn** [comment]
Fixed in 0eb2c6a21c thanks!
